### ISSUE TITLE
Thank you for this wonderful theme

### ISSUE THREAD

**Issue by overcatbe** [teamscops/bulmapress#1]
Hi, i love your work and plan on using the theme. 
Perhaps you could help me. 
I am using Atom with SASS Autocompile. 
The compiler has a problem with compiling your bulmapress.sass  to css, 
as it reads double files.
I know Atom Sass Autocompile needs these links in bulma to be able to compile, 
and i already prepared a version of bulma which works for me.
As your theme has a separate folder beginning with underscores, it is not a simple issue of linking the files together. 
I am not a programmer, and am pretty new to SASS. 
So hence my question - how are you compiling the bulmapress.sass? Thx much

**Comment by AlexKib** [comment]
Hey guys!
I have same problem here, but I use Sublime + ScoutApp. 
Have not found any workaround, but indeed I am in a great need of bulmapress for my project. Maybe someone can give an advice about how to compile it right?

**Comment by scorchio** [comment]
Hey @overcatbe & @AlexKib,

I've just met the same problem, but now I'm able to compile the bulmapress styles with the following:

1. In the frontend/bulmapress folder, create a package.json file with the following contents:
```
{
  "name": "bulmapress",
  "version": "0.1.0",
  "main": "bulmapress.sass",
  "devDependencies": {
    "autoprefixer": "^6.3.3",
    "captain-git-hook": "~1.0.5",
    "node-sass": "^3.4.2",
    "postcss-cli": "^2.5.1"
  },
  "scripts": {
    "build": "npm run build-clean && npm run build-sass && npm run build-autoprefix",
    "build-autoprefix": "postcss --use autoprefixer --output css/bulmapress.css css/bulmapress.css",
    "build-clean": "rm -rf css",
    "build-sass": "node-sass --output-style expanded --source-map true bulmapress.sass css/bulmapress.css",
    "deploy": "npm run build",
    "start": "npm run build-sass -- --watch",
  },
  "files": [
    "css",
    "sass",
    "bulmapress.sass"
  ]
}
```
2. Run `npm install` to install the dependencies for compiling SASS.
3. Once everything is installed, you can start compiling in watch mode with `npm run start` and you can compile the final files for production usage with `npm build`.

Hope this will help. Once I familiarize myself with bulmapress, I will perhaps open a PR with those modifications.

**Comment by raygervais** [comment]
@scorchio, did you ever get around to the PR? I ask because I noticed a need for this in my own projects as well and was curious if you had gotten around to it.

😄
