### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by jethromay** [teamscops/bulmapress#17]
Is this project dead or will it be maintained?

**Comment by crock** [comment]
My PR got merged the other day, so I'd say it is still alive. If @teamscops wants to abandon the project, I'll gladly take it over.

**Comment by eeegor** [comment]
@crock Hi Alex, let's chat! I would love to keep the project alive but am extremely busy with other topics.

**Comment by mysticaltech** [comment]
Website returns a 404

**Comment by crock** [comment]
@eeegor How would you like to chat? I’ll maintain the project for you.

**Comment by eeegor** [comment]
> Website returns a 404

Thanks, need to fix it!
