### ISSUE TITLE
Nav Walker Sub items not working

### ISSUE THREAD

**Issue by drastikrain** [teamscops/bulmapress#3]
Not much of a dev here, but the sub items in menus aren't seeming to be showing up for me.  
Does this work out of the box?  Is there somehting I'm missing?

Amazing work so far!  

- Nathan

**Comment by drastikrain** [comment]
Edit: it seems like Bulma hasn't ben updated to include navbar.  Damn.

**Comment by KayBeSee** [comment]
Did you ever figure this out?

**Comment by drastikrain** [comment]
Nope.  Just nixed Bulma as an option.



‌

*Nathan Sorochan*
A GOOD DESIGNER™

http://www.nathansorochan.com

*https://ca.linkedin.com/in/nathansorochan
<https://ca.linkedin.com/in/nathansorochan>*
Senior Designer at One Net Marketing <http://www.onenetmarketing.com> &
Cofounder/Marketing Lead at Whiffcraft Naturals <https://www.whiffcraft.ca>.

**Comment by KayBeSee** [comment]
Cool, I did too. Such a shame because it was such an uncluttered theme out of the box.

**Comment by drastikrain** [comment]
Agreed.  Coulda made magic with it - but not many people want a theme
that's broken out of the box. :)



‌

*Nathan Sorochan*
A GOOD DESIGNER™

http://www.nathansorochan.com

*https://ca.linkedin.com/in/nathansorochan
<https://ca.linkedin.com/in/nathansorochan>*
Senior Designer at One Net Marketing <http://www.onenetmarketing.com> &
Cofounder/Marketing Lead at Whiffcraft Naturals <https://www.whiffcraft.ca>.

**Comment by Yard8** [comment]
For reference here is a navwalker working with nested items:

https://github.com/Poruno/Bulma-Navwalker/blob/master/navwalker.php

**Comment by jethro-2018** [comment]
This is a much cleaner solution, which removes the need for having separate functions for the hamburger  button etc.

**Comment by eeegor** [comment]
@Yard8 @drastikrain @KayBeSee thanks for the kind words towards the theme and this is hopefully going to be fixed soon 🚀

**Comment by eeegor** [comment]
#21 coming in
