### ISSUE TITLE
How can I change the color primary color ?

### ISSUE THREAD

**Issue by harryevrard** [teamscops/bulmapress#4]
I uploaded the theme to wordpress but I'm not able to change the primary color.

**Comment by raygervais** [comment]
@harryevrard, I'm working on an update which references my PR #10 , enabling for a greater ease of changing attributes to Bulma.

**Comment by eeegor** [comment]
@harryevrard as this is a bit older now...

I assume you refer to the `customize` functionality within wordpress? This feature set has not yet been implemented, but would be a great enhancement. 

Will definitely be part of future releases
