### ISSUE TITLE
Where to add new SASS - and suggestion on directory structure.

### ISSUE THREAD

**Issue by Tanmccuin** [teamscops/bulmapress#5]
So i've spent some time going over the ins and outs of Bulma as well as Underscores - You've got a great job integrating the two. I have Prepos handling SASS compilation without much issue (other than pointing it at the correct bulmapress.css (it's slightly confusing that there are two bulmapress.css) 

My one big question is more related to responsive/workflow. In past SASS setups i've had a set of breakpoint files that handled styling at various breakpoints as well as a "base.sass" as sort of a catch-all. Looking through the organization of these files I don't see a clear base SASS file to start in - what would you suggest? and as far as styling for breakpoints, i gather that bulma has breakpoints 
http://bulma.io/documentation/overview/responsiveness/
but i'm not certain how they'd apply. Sorry if this is obvious - I figure it'd be better to go directly to the dev. Thanks!

**Comment by raygervais** [comment]
@Tanmccuin, if you are still curious or wishing to do so, my PR just landed which fixes this issue. I hope to have by later this week the final PR which adds the custom overrides needed (as an example), you can see what I'm talking about here: #12 

If you have any other questions regarding SASS / Directory Structure I can try to help, it appears I'm slowly reviving the project with help from original @teamscops members 😄

**Comment by eeegor** [comment]
Closing as has been merged
